on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Angular app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-verion: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: |
          npm run-script "ng build --configuration production --base-href https://daily-illini.github.io/salary-guide-widget/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/salary-guide-widget/
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1
